name: DartAdvancedTutorials
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: raouf <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: ^0.15.7


#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
